apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: git-faas-layer
  namespace: default
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: "enabled"
        autoscaling.knative.dev/window: "120s"
        autoscaling.knative.dev/target: "10"
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/gitsynapse/gitsynapse-repo/git-faas-layer:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-credentials
                  key: token
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: gcs-workspaces
              mountPath: /mnt/workspaces
      volumes:
        - name: gcs-workspaces
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: gitsynapse-workspaces
              mountOptions: "implicit-dirs"
